name: Build

on:
  - push
  - pull_request

permissions:
  contents: write

jobs:
  build_plugin:
    name: Build Plugin
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      #build tomoon start
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip

      - uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: pnpm

      - name: Install package and build
        run: |
          pnpm install --no-frozen-lockfile
          pnpm build

      - name: Collect files
        run: |
          mkdir -p release/DeckyClash
          cp -R default/* ./release/DeckyClash/
          cp -R dist ./release/DeckyClash/
          cp -R py_modules ./release/DeckyClash/
          cp main.py ./release/DeckyClash/main.py
          cp plugin.json ./release/DeckyClash/plugin.json
          cp package.json ./release/DeckyClash/package.json
          cd ./release 
          zip -r DeckyClash.zip DeckyClash
          cd ..

      - name: Publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deckyclash-artifacts
          path: ./release/DeckyClash.zip
          if-no-files-found: error


  publish:
    name: Publish release
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: build_plugin
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Publish to Github release
        uses: softprops/action-gh-release@v2
        with:
          files: ./artifacts/deckyclash-artifacts/DeckyClash.zip
          name: Release ${{ github.ref_name }}
          draft: false
          generate_release_notes: true
          prerelease: ${{ contains(github.ref, 'pre') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
